<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?php echo $this->title; ?></title>
    </head>
    <body>
        <div id="nav"><?php echo $this->navigation(); ?></div>
        <h1><?php echo $this->title; ?></h1>
        <div id="content"><?php echo $this->layout()->content; ?></div>
    </body>
</html>