<?php

namespace Application\Entity;

use Application\Entity\CrudRepository;

/**
 * AutorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutorRepository extends CrudRepository
{
    /**
     * Retorna todas Autors cadastradas como array ([id]nome)
     * @return array
     */
    public function getArrayAutores()
    {
        foreach ($this->findAll() as $autor) {
            $autores[$autor->getId()] = $autor->getNome();
        }
        return $autores;
    }
}