<?php

namespace Application\Entity;

use Application\Entity\CrudRepository;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends CrudRepository
{
    /**
     * Retorna todas categorias cadastradas como array ([id]nome)
     * @return array
     */
    public function getArrayCategorias()
    {
        foreach ($this->findAll() as $categoria) {
            $categorias[$categoria->getId()] = $categoria->getNome();
        }
        return $categorias;
    }
}